mask=Im;
mask(mask<220)=0;
mask(mask>=220)=255;
mask=255-mask;
mask = bwareaopen(mask,100);
se90 = strel('line',10,90);
se0 = strel('line',10,0);
mask = imdilate(mask,[se90 se0]);
%mask = bwareaopen(mask,10);
seD = strel('diamond',10);
mask=imfill(mask,'holes');
mask = imdilate(mask,seD);
mask=imfill(mask,'holes');
mask = imerode(mask,[se90 se0]);
mask = imerode(mask,[se90 se0]);
%mask = imerode(mask,[se90 se0]);
%mask = imerode(mask,seD);
mask = imerode(mask,seD);
mask=imfill(mask,'holes');
mask = bwareaopen(mask,5000);
%mask = imclearborder(mask,8);
figure;imshow(mask);